# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('restaurants', '0002_coursename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.CourseName')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
