# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_course_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Group',
            new_name='CourseGroup',
        ),
        migrations.RenameModel(
            old_name='User_Group',
            new_name='UserGroup',
        ),
    ]
